project/config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    resources :reasons
  end
  get "/reasons" => "reasons#index"
  devise_for :users

  root to: "activities#index"

end

project/app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :reasons
end

project/app/models/reason.rb
class Reason < ActiveRecord::Base
  belongs_to :activity
end

project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end
  def menber?
    self.role == "menber"
  end
end

project/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @time = Time.now
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: '活动已被成功创建。' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: '活动已被成功修改。' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @reason = @activity.reasons
    @reason.each do |reason|
        reason.destroy
    end
    @activity.destroy 
    respond_to do |format|
      format.html { redirect_to activities_url, notice: '活动已被成功删除。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :content, :date, :originator)
    end
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate_admin
    unless current_user.admin?
      # flash[:alert] = "Not allow"
      redirect_to root_path
    end
  end

end

project/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

project/app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @activity = Activity.find(params[:activity_id])
    @reason = @activity.reasons.create(reason_params)
    redirect_to activities_path
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: '请假原因已被成功修改。' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: '请假原因已被成功删除。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:name, :why)
    end
end

project/app/helpers/activities_helper.rb
module ActivitiesHelper
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/home_helper.rb
module HomeHelper
end

project/app/helpers/reasons_helper.rb
module ReasonsHelper
end

project/app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "个") %> 错误出现了:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui form">
    <div class="twelve wide field" style="position:relative;left:12%">
      <%= f.label :活动标题 %>
      <%= f.text_field :title %>
    </div>
    <div class="twelve wide field" style="position:relative;left:12%">
      <%= f.label :活动内容 %>
      <%= f.text_area :content, size: "10x2" %>
    </div>
  </div>
  <br>
    <div class="field" style="font-weight:700">
      <%= f.label :活动时间 %><br>
      <%#= f.datetime_select :date %>
      <%= datetime_select("activity", "date", default: 0.days.from_now) %>
    </div>
    <br>
    <div class="ui form">
      <div class="twelve wide field" style="position:relative;left:12%">
        <%= f.label :发起人 %>
        <%= f.text_field :originator %>
      </div>
      <div class="actions">
        <%= f.submit '提交活动'%>
      </div>
    </div>

<% end %>

project/app/views/activities/edit.html.erb
<div class="main" style = "text-align: center">
  <h1>修改活动</h1>
  <%= render 'form' %>
</div>

<div class="bottom">
  <%= link_to '返回列表', @activity %> |
  <%= link_to '返回主页', activities_path %>
</div>

project/app/views/activities/index.html.erb
<div class="list">
  <div class="ui center aligned container">
    <table class="ui unstackable inverted teal table" style = " width: 100%; height: 100%">
      <thead>
        <tr>
          <th>活动标题</th>
          <th>活动日期</th>
          <th>发起人</th>
          <th>活动请假</th>
          <% if current_user.admin? %>
          <th>编辑活动</th>
          <th>删除活动</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @activities.each do |activity| %>
        <tr>
          <td><%= activity.title %></td>
          <td><%= activity.date.strftime('%Y-%m-%d %H:%M') %></td>
          <td><%= activity.originator %></td>
          <td><%= link_to '活动请假', activity %></td>
          <% if current_user.admin? %>
          <td><%= link_to '编辑活动', edit_activity_path(activity) %></td>
          <td><%= link_to '删除活动', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="bottom">
    <% if current_user.admin? %>
    <%= link_to '新建活动', new_activity_path %> |
    <%= link_to '查看请假原因', reasons_path%>
    <% end %>
</div>

project/app/views/activities/new.html.erb
<div class="main" style = "text-align: center">
  <h1>新建活动</h1>
  <%= render 'form' %>
</div>

<div class="bottom">
  <%= link_to '返回主页', activities_path %>
</div>

project/app/views/activities/show.html.erb
<div class="list">
  <div class="grid" style="font-size:17px">
    <div class="sixteen wide column">
      <p>
        <strong>活动标题:</strong>
        <%= @activity.title %>
      </p>
    </div>
  </hr>
    <div class="sixteen wide column">
        <p>
          <strong>活动内容:</strong>
          <p style="border: solid 2px transparent;position: relative; margin-top: -5%;word-wrap:break-word">
            <%= @activity.content.gsub(/\n/,'</br>').html_safe %>
          </p>
        </p>
    </div>
  </hr>
      <div class="ten wide column">
        <p>
          <strong>活动时间:</strong>
          <%= @activity.date.strftime('%Y-%m-%d %H:%M') %>
        </p>
      </div>
      <div class="four column">
        <p>
          <strong>发起人:</strong>
          <%= @activity.originator %>
        </p>
      </div>
    </div>
    <%# if current_user.menber? and (@time - @activity.date.ago(1.day) < 0) %>
    <% if (@time - @activity.date.ago(1.day) < 0) %>
    <h2> 想要请假吗? </h2>
    <%= form_for([@activity, @activity.reasons.build]) do |f| %>
    <div class="ui form" >
      <div class="twelve wide field" style="position:relative;">
        <%= f.label :姓名 %>
        <%= f.text_field :name %>
      </div>
    <div class="twelve wide field" style="position:relative;">
      <%= f.label :请假原因 %>
      <%= f.text_area :why, size: "10x5" %>
    </div>
    </div>
    <br>
    <button class="ui teal button" type="submit" style="font-size:14px;position:relative; left: 60%">
      请假
    </button>
    <% end %>

    <% end %>
  </div>
<div class="bottom">
  <% if current_user.admin? %>
  <%= link_to '编辑活动', edit_activity_path(@activity) %> |
  <% end %>
  <%= link_to '返回主页', activities_path %>
</div>

project/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>信息传媒部请假平台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= link_to('退出登录', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密码', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('注册', new_registration_path(:user)) %> |
    <%= link_to('登录', new_session_path(:user)) %>
<% end %>
  <input type = "hidden" id="user" value="<%= notice %>">
  <input type = "hidden" id="log" value="<%= alert %>">
<%= yield %>
</body>
</html>

project/app/views/reasons/edit.html.erb
<h1>编辑请假原因</h1>

<%= render 'form' %>

<%= link_to '返回', @reason %> |
<%= link_to '返回原因列表', reasons_path %>

project/app/views/reasons/index.html.erb
<div class="main">
  <h1>请假原因列表</h1>

  <table class="ui inverted teal table">
    <thead>
      <tr>
        <th>姓名</th>
        <th>请假原因</th>
        <th>活动名称</th>
        <th>查看详情</th>
        <th>删除</th>
      </tr>
    </thead>

    <tbody>
      <% @reasons.each do |reason| %>
      
      <tr>
        <td><%= reason.name %></td>
        <td><%= reason.why %></td>
        <td><%= reason.activity.title %></td>
        <td><%= link_to '详情', activity_reason_path(reason.activity,reason) %></td>
        <td><%= link_to '删除', activity_reason_path(reason.activity,reason), method: :delete, data: { confirm: '确定要删除此条请假吗?' } %></td>
      </tr>
      
<% end %>
    </tbody>
  </table>
</div>
<div class="bottom">
  <%= link_to '返回主页', activities_path %>
</div>

project/app/views/reasons/show.html.erb
<div class="main">
  <div class="grid" style="font-size:17px">
  <div class="sixteen wide column">

    <strong>姓名:</strong>
    <%= @reason.name %>
  </div>
  <div class="sixteen wide column">
    <strong>请假原因:</strong>
    <%= @reason.why %>
  </div>
  <div class="sixteen wide column">
    <strong>活动名称:</strong>
    <%= @reason.activity.title %>
  </div>
  </div>
</div>

<div class="bottom">
  <%= link_to '返回', reasons_path %>
</div>